[platformio]
default_envs = nodemcuv2
description = OpenRF Platform v1.1.0

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    jgromes/RadioLib
    knolleary/PubSubClient
    bblanchon/ArduinoJson

build_flags =
    -D OPENRF_STABLE_RELEASE=1
