[platformio]
default_envs = esp32s3

description = OpenRF Platform v1.2.0 - ESP32-S3 N16R8 Dual-Core

[env:esp32s3]
platform = espressif32
board = openrf-esp32-s3-n16r8
framework = arduino

monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    jgromes/RadioLib
    knolleary/PubSubClient
    bblanchon/ArduinoJson

build_flags =
    -D OPENRF_STABLE_RELEASE=1
